# Generated by Django 4.2.5 on 2023-09-18 16:54

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.CharField(max_length=200, verbose_name='اسم المدرس')),
                ('coures_name', models.CharField(max_length=300, verbose_name='اسم المادة')),
                ('class_type', models.CharField(choices=[('ابتدائي', 'ابتدائي'), ('اعدادي', 'اعدادي'), ('ثانوي', 'ثانوي')], max_length=50, verbose_name='المرحلة')),
                ('class_number', models.PositiveIntegerField(verbose_name='السنة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='السعر')),
                ('days', multiselectfield.db.fields.MultiSelectField(choices=[('الاثنين', 'الاثنين'), ('الثلاثاء', 'الثلاثاء'), ('الاربع', 'الاربع'), ('الخميس', 'الخميس'), ('الجمعة', 'الجمعة'), ('السبت', 'السبت'), ('الحد', 'الحد')], max_length=56, verbose_name='الايام')),
                ('details', models.CharField(blank=True, default='لا يوجد تفاصيل اخري ', max_length=2000, null=True, verbose_name='تفاصيل ')),
                ('hour', models.DecimalField(decimal_places=2, max_digits=5, validators=[website.models.validate_hour, django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='المعاد')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': ' درس',
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.CharField(max_length=200, verbose_name='اسم المدرب')),
                ('coures_name', models.CharField(max_length=300, verbose_name='اسم الكورس')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('days', multiselectfield.db.fields.MultiSelectField(choices=[('الاثنين', 'الاثنين'), ('الثلاثاء', 'الثلاثاء'), ('الاربع', 'الاربع'), ('الخميس', 'الخميس'), ('الجمعة', 'الجمعة'), ('السبت', 'السبت'), ('الحد', 'الحد')], max_length=56, verbose_name='الايام')),
                ('details', models.CharField(blank=True, default='لا يوجد تفاصيل اخري ', max_length=2000, null=True, verbose_name='تفاصيل ')),
                ('hour', models.DecimalField(decimal_places=2, max_digits=5, validators=[website.models.validate_hour, django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='المعاد')),
            ],
            options={
                'verbose_name': 'تدريب',
                'verbose_name_plural': 'تدريب',
            },
        ),
    ]
